[package]
name = "fzf"
version = "0.54.0"
description = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
repository = "https://github.com/junegunn/fzf"

[dependencies]

[install]
type = "binary"
url = "https://github.com/junegunn/fzf/releases/download/{{version}}/fzf-{{version}}-linux_amd64.tar.gz"
strip_prefix = ""
bin = ["fzf"]
